version: '3.8'

services:
  gdlwebui-client:
    container_name: gdlwebui-client
    build: .
    ports:
      - 80:80
    restart: unless-stopped
  gdlwebui-server:
    container_name: gdlwebui-server
    volumes:
      - ./gallery-dl:/usr/src/app/gallery-dl

      # optional
      # - type: bind
      #   source: path/to/gallery-dl.conf
      #   target: /usr/src/app/gallery-dl.conf

      # - path/to/cookies/directory:/usr/src/app/cookies # optional
    build: server/.
    restart: unless-stopped
